//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoSQLBeerCore.SqlServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OpenBeerDatabaseEntities : DbContext
    {
        public OpenBeerDatabaseEntities()
            : base("name=OpenBeerDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<beers> beers { get; set; }
        public DbSet<breweries> breweries { get; set; }
        public DbSet<breweries_geocode> breweries_geocode { get; set; }
        public DbSet<styles> styles { get; set; }
    }
}
