//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoSQLBeerCore.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class beers
    {
        public int ID { get; set; }
        public int brewery_id { get; set; }
        public string name { get; set; }
        public int style_id { get; set; }
        public double abv { get; set; }
        public double srm { get; set; }
        public int upc { get; set; }
        public string descript { get; set; }
    
        public virtual breweries breweries { get; set; }
        public virtual styles styles { get; set; }
    }
}
