//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoSQLBeerCore.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class breweries_geocode
    {
        public int ID { get; set; }
        public int brewery_id { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string accuracy { get; set; }
    
        public virtual breweries breweries { get; set; }
    }
}
